name: Actualizar Tapas

on:
  schedule:
    - cron: '30 8 * * *' # Correrá a las 05:30 AM Argentina
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python scraper.py
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tapas.json
          git commit -m "Tapas actualizadas" || exit 0
          git push
